import { relations, sql } from 'drizzle-orm'
import {
  boolean,
  customType,
  doublePrecision,
  index,
  integer,
  pgTable,
  primaryKey,
  text,
  timestamp,
  unique,
  uniqueIndex,
} from 'drizzle-orm/pg-core'

/** Postgres `bytea` — raw binary, used for uploaded recipe images. */
const bytea = customType<{ data: Uint8Array; driverData: Buffer }>({
  dataType() {
    return 'bytea'
  },
})

/* -------------------------------------------------------------------------- */
/*  better-auth tables                                                        */
/*  Column/field names match better-auth's defaults so the drizzle adapter    */
/*  can map them automatically. Generated by hand to match better-auth 1.6.   */
/* -------------------------------------------------------------------------- */

export const user = pgTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified')
    .$defaultFn(() => false)
    .notNull(),
  image: text('image'),
  createdAt: timestamp('created_at')
    .$defaultFn(() => new Date())
    .notNull(),
  updatedAt: timestamp('updated_at')
    .$defaultFn(() => new Date())
    .notNull(),
})

export const session = pgTable('session', {
  id: text('id').primaryKey(),
  expiresAt: timestamp('expires_at').notNull(),
  token: text('token').notNull().unique(),
  createdAt: timestamp('created_at').notNull(),
  updatedAt: timestamp('updated_at').notNull(),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
})

export const account = pgTable('account', {
  id: text('id').primaryKey(),
  accountId: text('account_id').notNull(),
  providerId: text('provider_id').notNull(),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  idToken: text('id_token'),
  accessTokenExpiresAt: timestamp('access_token_expires_at'),
  refreshTokenExpiresAt: timestamp('refresh_token_expires_at'),
  scope: text('scope'),
  password: text('password'),
  createdAt: timestamp('created_at').notNull(),
  updatedAt: timestamp('updated_at').notNull(),
})

export const verification = pgTable('verification', {
  id: text('id').primaryKey(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: timestamp('expires_at').notNull(),
  createdAt: timestamp('created_at').$defaultFn(() => new Date()),
  updatedAt: timestamp('updated_at').$defaultFn(() => new Date()),
})

/* -------------------------------------------------------------------------- */
/*  Recipe tables                                                             */
/* -------------------------------------------------------------------------- */

export const recipe = pgTable('recipe', {
  id: text('id')
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  title: text('title').notNull(),
  description: text('description'),
  /** For "linked" recipes that live on an external site. */
  sourceUrl: text('source_url'),
  imageUrl: text('image_url'),
  /** Free-form preparation steps (markdown / plain text). Empty for linked-only recipes. */
  instructions: text('instructions'),
  servings: integer('servings'),
  /** Postgres text[] of free-form tags, used for search/filtering. */
  tags: text('tags')
    .array()
    .notNull()
    .default(sql`'{}'::text[]`),
  /**
   * The user who owns this recipe. Recipes are private to the owner unless the
   * owner shares access to their collection via {@link accessGrant}. (DB column
   * kept as `created_by` from the original shared-collection model.)
   */
  ownerId: text('created_by')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  createdAt: timestamp('created_at')
    .$defaultFn(() => new Date())
    .notNull(),
  updatedAt: timestamp('updated_at')
    .$defaultFn(() => new Date())
    .notNull(),
})

export const ingredient = pgTable('ingredient', {
  id: text('id')
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  recipeId: text('recipe_id')
    .notNull()
    .references(() => recipe.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  /** Numeric amount, e.g. 2 (null when not quantified, e.g. "salt to taste"). */
  quantity: doublePrecision('quantity'),
  /** Unit of measure, e.g. "g", "cups", "tbsp". */
  unit: text('unit'),
  /** Optional note, e.g. "finely chopped". */
  note: text('note'),
  /**
   * Optional sub-recipe / component this ingredient belongs to, e.g. "Saus" or
   * "Kylling". Purely a display grouping on the recipe — the shopping list
   * aggregates by item key across components, so it never affects totals. Null =
   * ungrouped.
   */
  component: text('component'),
  sortOrder: integer('sort_order').notNull().default(0),
})

/**
 * Households group users who share everything. A user with no row here is their
 * own household (scope = their own id). When someone accepts an invite they
 * join the inviter's household, so all members share recipes and one shopping
 * list.
 */
export const householdMember = pgTable('household_member', {
  userId: text('user_id')
    .primaryKey()
    .references(() => user.id, { onDelete: 'cascade' }),
  /** Shared scope id (the household). Defaults to the founding user's id. */
  householdId: text('household_id').notNull(),
  createdAt: timestamp('created_at')
    .$defaultFn(() => new Date())
    .notNull(),
})

/**
 * A pending invitation from one user to another (identified by email). No email
 * is sent — the invitee sees it as a notification on login. Consumed (deleted)
 * on accept/decline.
 */
export const invite = pgTable(
  'invite',
  {
    id: text('id')
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    fromUserId: text('from_user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    /** Invitee email, stored lowercased. */
    toEmail: text('to_email').notNull(),
    createdAt: timestamp('created_at')
      .$defaultFn(() => new Date())
      .notNull(),
  },
  (t) => [unique('invite_from_to_uq').on(t.fromUserId, t.toEmail)],
)

/**
 * Persisted "ticked off" state for the generated shopping list, scoped to a
 * household so members share one list. Keyed by scope + normalized item key
 * (name + unit) so it survives recipe re-aggregation. The scope id is a
 * household id (which is always some user's id, hence the `user_id` column /
 * FK kept from an earlier per-user iteration).
 */
export const shoppingCheck = pgTable(
  'shopping_check',
  {
    /**
     * Household id (shared scope) — a generated id for shared households, or the
     * user's own id when solo. Not a FK: it's an opaque scope key.
     */
    scopeId: text('user_id').notNull(),
    itemKey: text('item_key').notNull(),
    checked: boolean('checked').notNull().default(false),
    /**
     * Optional manual quantity for the aggregated line. When set, it replaces
     * the quantity summed from the contributing entries on display (the entries
     * themselves are untouched, so recipe linkage / "on the list" status are
     * preserved). Null means "use the computed sum". Lives here, keyed by
     * (scope, item_key), so it survives recipe re-aggregation just like `checked`.
     */
    overrideQuantity: doublePrecision('override_quantity'),
    updatedAt: timestamp('updated_at')
      .$defaultFn(() => new Date())
      .notNull(),
  },
  (t) => [primaryKey({ columns: [t.scopeId, t.itemKey] })],
)

/**
 * The materialized shopping list: one row per ingredient *contribution*, scoped
 * to a household. Items get here explicitly — either added from a recipe
 * ({@link sourceRecipeId} set) or typed in ad-hoc ({@link sourceRecipeId} null).
 * They persist independently of any recipe state; only an explicit remove takes
 * them off the list.
 *
 * The list shown to users aggregates these by {@link itemKey} (normalized
 * name + unit), summing quantities — so two recipes both needing garlic merge
 * into one line. The stored `itemKey` mirrors the server's `itemKey()` helper so
 * aggregation and the {@link shoppingCheck} "ticked off" rows line up exactly.
 */
export const shoppingEntry = pgTable(
  'shopping_entry',
  {
    id: text('id')
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    /** Household id (shared scope) — same opaque scope key as {@link shoppingCheck}. */
    scopeId: text('scope_id').notNull(),
    /** Normalized `name__unit`, computed at insert time. Groups contributions into one line. */
    itemKey: text('item_key').notNull(),
    name: text('name').notNull(),
    quantity: doublePrecision('quantity'),
    unit: text('unit'),
    note: text('note'),
    /** The recipe this came from; null for ad-hoc items. Cleared (not deleted) if the recipe is removed. */
    sourceRecipeId: text('source_recipe_id').references(() => recipe.id, {
      onDelete: 'set null',
    }),
    /** Denormalized recipe title for display — survives recipe edits/deletion. Null for ad-hoc items. */
    sourceTitle: text('source_title'),
    createdAt: timestamp('created_at')
      .$defaultFn(() => new Date())
      .notNull(),
    updatedAt: timestamp('updated_at')
      .$defaultFn(() => new Date())
      .notNull(),
  },
  (t) => [
    index('shopping_entry_scope_idx').on(t.scopeId),
    index('shopping_entry_source_idx').on(t.sourceRecipeId),
  ],
)

/**
 * An uploaded image for a recipe, stored as bytes in Postgres (one per recipe).
 * Kept in its own table so the blob is never loaded by ordinary recipe queries —
 * it's served only through the `/api/recipes/$recipeId/image` route. A recipe
 * either has an uploaded image here OR an external `recipe.image_url`, never both
 * (the form keeps them mutually exclusive).
 */
export const recipeImage = pgTable('recipe_image', {
  recipeId: text('recipe_id')
    .primaryKey()
    .references(() => recipe.id, { onDelete: 'cascade' }),
  contentType: text('content_type').notNull(),
  data: bytea('data').notNull(),
  byteSize: integer('byte_size').notNull(),
  // timestamptz so the cache-busting `?v=<updatedAt>` is an unambiguous instant
  // (a plain `timestamp` round-trips with a timezone offset between drivers).
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .$defaultFn(() => new Date())
    .notNull(),
})

/**
 * A household member's 1–10 rating of a recipe (one per user per recipe). The
 * overview orders by the sum of these; the detail page shows each member's vote
 * plus the aggregate. Only members who can access a recipe may rate it.
 */
export const recipeRating = pgTable(
  'recipe_rating',
  {
    recipeId: text('recipe_id')
      .notNull()
      .references(() => recipe.id, { onDelete: 'cascade' }),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    /** 1–10. */
    score: integer('score').notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .$defaultFn(() => new Date())
      .notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.recipeId, t.userId] }),
    index('recipe_rating_recipe_idx').on(t.recipeId),
  ],
)

/**
 * A saved ingredient for the add-to-shopping-list autocomplete (distinct from
 * {@link ingredient}, which holds a recipe's ingredient lines). Two kinds of
 * rows coexist, told apart by {@link scopeId}:
 *   - **stock** (`scope_id` NULL): curated ingredients that belong to no one,
 *     seeded into the DB; visible to everyone.
 *   - **household** (`scope_id` = household id): ingredients a member typed in
 *     that the autocomplete didn't already know, visible only within that
 *     household. A household row with the same name shadows a stock row.
 *
 * {@link category} groups the ingredient under a header on the shopping list
 * (see `src/lib/categories.ts`). {@link nameKey} is the lower-cased name used for
 * lookup/dedup. Partial unique indexes keep one row per name within each kind.
 */
export const ingredientCatalog = pgTable(
  'ingredient_catalog',
  {
    id: text('id')
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    /** NULL = stock (belongs to no one); otherwise the household scope id. */
    scopeId: text('scope_id'),
    name: text('name').notNull(),
    /** Normalized lower-case name, for lookup and dedup. */
    nameKey: text('name_key').notNull(),
    /** Grocery category for shopping-list grouping; see `src/lib/categories.ts`. */
    category: text('category').notNull().default('Annet'),
    createdAt: timestamp('created_at')
      .$defaultFn(() => new Date())
      .notNull(),
  },
  (t) => [
    index('ingredient_catalog_name_idx').on(t.nameKey),
    // One stock row per name; one household row per (household, name). NULL
    // scopes are excluded from the household index (and vice-versa) so the two
    // kinds never collide.
    uniqueIndex('ingredient_catalog_stock_uq')
      .on(t.nameKey)
      .where(sql`scope_id is null`),
    uniqueIndex('ingredient_catalog_scope_uq')
      .on(t.scopeId, t.nameKey)
      .where(sql`scope_id is not null`),
  ],
)

/**
 * Admin-created categories that persist on their own (independently of whether
 * any ingredient currently uses them). The full set of categories shown in the
 * app is the canonical list in `src/lib/categories.ts` ∪ these rows ∪ whatever
 * categories appear on {@link ingredientCatalog} rows. Global (not scoped).
 */
export const ingredientCategory = pgTable('ingredient_category', {
  name: text('name').primaryKey(),
  createdAt: timestamp('created_at')
    .$defaultFn(() => new Date())
    .notNull(),
})

/* -------------------------------------------------------------------------- */
/*  Relations                                                                 */
/* -------------------------------------------------------------------------- */

export const recipeRelations = relations(recipe, ({ one, many }) => ({
  ingredients: many(ingredient),
  owner: one(user, {
    fields: [recipe.ownerId],
    references: [user.id],
  }),
}))

export const ingredientRelations = relations(ingredient, ({ one }) => ({
  recipe: one(recipe, {
    fields: [ingredient.recipeId],
    references: [recipe.id],
  }),
}))

export type Recipe = typeof recipe.$inferSelect
export type NewRecipe = typeof recipe.$inferInsert
export type Ingredient = typeof ingredient.$inferSelect
export type NewIngredient = typeof ingredient.$inferInsert
export type Invite = typeof invite.$inferSelect
export type HouseholdMember = typeof householdMember.$inferSelect
export type ShoppingEntry = typeof shoppingEntry.$inferSelect
export type NewShoppingEntry = typeof shoppingEntry.$inferInsert
export type RecipeImage = typeof recipeImage.$inferSelect
export type RecipeRating = typeof recipeRating.$inferSelect
export type IngredientCatalog = typeof ingredientCatalog.$inferSelect
export type NewIngredientCatalog = typeof ingredientCatalog.$inferInsert
export type IngredientCategoryRow = typeof ingredientCategory.$inferSelect
