import { relations, sql } from 'drizzle-orm'
import {
  boolean,
  doublePrecision,
  integer,
  pgTable,
  text,
  timestamp,
} from 'drizzle-orm/pg-core'

/* -------------------------------------------------------------------------- */
/*  better-auth tables                                                        */
/*  Column/field names match better-auth's defaults so the drizzle adapter    */
/*  can map them automatically. Generated by hand to match better-auth 1.6.   */
/* -------------------------------------------------------------------------- */

export const user = pgTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified')
    .$defaultFn(() => false)
    .notNull(),
  image: text('image'),
  createdAt: timestamp('created_at')
    .$defaultFn(() => new Date())
    .notNull(),
  updatedAt: timestamp('updated_at')
    .$defaultFn(() => new Date())
    .notNull(),
})

export const session = pgTable('session', {
  id: text('id').primaryKey(),
  expiresAt: timestamp('expires_at').notNull(),
  token: text('token').notNull().unique(),
  createdAt: timestamp('created_at').notNull(),
  updatedAt: timestamp('updated_at').notNull(),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
})

export const account = pgTable('account', {
  id: text('id').primaryKey(),
  accountId: text('account_id').notNull(),
  providerId: text('provider_id').notNull(),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  idToken: text('id_token'),
  accessTokenExpiresAt: timestamp('access_token_expires_at'),
  refreshTokenExpiresAt: timestamp('refresh_token_expires_at'),
  scope: text('scope'),
  password: text('password'),
  createdAt: timestamp('created_at').notNull(),
  updatedAt: timestamp('updated_at').notNull(),
})

export const verification = pgTable('verification', {
  id: text('id').primaryKey(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: timestamp('expires_at').notNull(),
  createdAt: timestamp('created_at').$defaultFn(() => new Date()),
  updatedAt: timestamp('updated_at').$defaultFn(() => new Date()),
})

/* -------------------------------------------------------------------------- */
/*  Recipe tables                                                             */
/* -------------------------------------------------------------------------- */

export const recipe = pgTable('recipe', {
  id: text('id')
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  title: text('title').notNull(),
  description: text('description'),
  /** For "linked" recipes that live on an external site. */
  sourceUrl: text('source_url'),
  imageUrl: text('image_url'),
  /** Free-form preparation steps (markdown / plain text). Empty for linked-only recipes. */
  instructions: text('instructions'),
  servings: integer('servings'),
  /** Postgres text[] of free-form tags, used for search/filtering. */
  tags: text('tags')
    .array()
    .notNull()
    .default(sql`'{}'::text[]`),
  /** Marked as part of this week's meal plan. */
  isActive: boolean('is_active').notNull().default(false),
  createdBy: text('created_by').references(() => user.id, {
    onDelete: 'set null',
  }),
  createdAt: timestamp('created_at')
    .$defaultFn(() => new Date())
    .notNull(),
  updatedAt: timestamp('updated_at')
    .$defaultFn(() => new Date())
    .notNull(),
})

export const ingredient = pgTable('ingredient', {
  id: text('id')
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  recipeId: text('recipe_id')
    .notNull()
    .references(() => recipe.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  /** Numeric amount, e.g. 2 (null when not quantified, e.g. "salt to taste"). */
  quantity: doublePrecision('quantity'),
  /** Unit of measure, e.g. "g", "cups", "tbsp". */
  unit: text('unit'),
  /** Optional note, e.g. "finely chopped". */
  note: text('note'),
  sortOrder: integer('sort_order').notNull().default(0),
})

/**
 * Persisted "ticked off" state for the generated shopping list. Keyed by a
 * normalized item key (name + unit) so it survives recipe re-aggregation.
 */
export const shoppingCheck = pgTable('shopping_check', {
  itemKey: text('item_key').primaryKey(),
  checked: boolean('checked').notNull().default(false),
  updatedAt: timestamp('updated_at')
    .$defaultFn(() => new Date())
    .notNull(),
})

/* -------------------------------------------------------------------------- */
/*  Relations                                                                 */
/* -------------------------------------------------------------------------- */

export const recipeRelations = relations(recipe, ({ many }) => ({
  ingredients: many(ingredient),
}))

export const ingredientRelations = relations(ingredient, ({ one }) => ({
  recipe: one(recipe, {
    fields: [ingredient.recipeId],
    references: [recipe.id],
  }),
}))

export type Recipe = typeof recipe.$inferSelect
export type NewRecipe = typeof recipe.$inferInsert
export type Ingredient = typeof ingredient.$inferSelect
export type NewIngredient = typeof ingredient.$inferInsert
