/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedShoppingRouteImport } from './routes/_authed/shopping'
import { Route as AuthedDelingRouteImport } from './routes/_authed/deling'
import { Route as AuthedRecipesIndexRouteImport } from './routes/_authed/recipes/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedRecipesNewRouteImport } from './routes/_authed/recipes/new'
import { Route as AuthedRecipesRecipeIdRouteImport } from './routes/_authed/recipes/$recipeId'
import { Route as AuthedRecipesRecipeIdEditRouteImport } from './routes/_authed/recipes/$recipeId_.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedShoppingRoute = AuthedShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDelingRoute = AuthedDelingRouteImport.update({
  id: '/deling',
  path: '/deling',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRecipesIndexRoute = AuthedRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRecipesNewRoute = AuthedRecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRecipesRecipeIdRoute = AuthedRecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRecipesRecipeIdEditRoute =
  AuthedRecipesRecipeIdEditRouteImport.update({
    id: '/recipes/$recipeId_/edit',
    path: '/recipes/$recipeId/edit',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/deling': typeof AuthedDelingRoute
  '/shopping': typeof AuthedShoppingRoute
  '/recipes/$recipeId': typeof AuthedRecipesRecipeIdRoute
  '/recipes/new': typeof AuthedRecipesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/recipes/': typeof AuthedRecipesIndexRoute
  '/recipes/$recipeId/edit': typeof AuthedRecipesRecipeIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/deling': typeof AuthedDelingRoute
  '/shopping': typeof AuthedShoppingRoute
  '/recipes/$recipeId': typeof AuthedRecipesRecipeIdRoute
  '/recipes/new': typeof AuthedRecipesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/recipes': typeof AuthedRecipesIndexRoute
  '/recipes/$recipeId/edit': typeof AuthedRecipesRecipeIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/deling': typeof AuthedDelingRoute
  '/_authed/shopping': typeof AuthedShoppingRoute
  '/_authed/recipes/$recipeId': typeof AuthedRecipesRecipeIdRoute
  '/_authed/recipes/new': typeof AuthedRecipesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/recipes/': typeof AuthedRecipesIndexRoute
  '/_authed/recipes/$recipeId_/edit': typeof AuthedRecipesRecipeIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/deling'
    | '/shopping'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/api/auth/$'
    | '/recipes/'
    | '/recipes/$recipeId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/deling'
    | '/shopping'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/api/auth/$'
    | '/recipes'
    | '/recipes/$recipeId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/deling'
    | '/_authed/shopping'
    | '/_authed/recipes/$recipeId'
    | '/_authed/recipes/new'
    | '/api/auth/$'
    | '/_authed/recipes/'
    | '/_authed/recipes/$recipeId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/shopping': {
      id: '/_authed/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof AuthedShoppingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/deling': {
      id: '/_authed/deling'
      path: '/deling'
      fullPath: '/deling'
      preLoaderRoute: typeof AuthedDelingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recipes/': {
      id: '/_authed/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AuthedRecipesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/recipes/new': {
      id: '/_authed/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof AuthedRecipesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recipes/$recipeId': {
      id: '/_authed/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof AuthedRecipesRecipeIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recipes/$recipeId_/edit': {
      id: '/_authed/recipes/$recipeId_/edit'
      path: '/recipes/$recipeId/edit'
      fullPath: '/recipes/$recipeId/edit'
      preLoaderRoute: typeof AuthedRecipesRecipeIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDelingRoute: typeof AuthedDelingRoute
  AuthedShoppingRoute: typeof AuthedShoppingRoute
  AuthedRecipesRecipeIdRoute: typeof AuthedRecipesRecipeIdRoute
  AuthedRecipesNewRoute: typeof AuthedRecipesNewRoute
  AuthedRecipesIndexRoute: typeof AuthedRecipesIndexRoute
  AuthedRecipesRecipeIdEditRoute: typeof AuthedRecipesRecipeIdEditRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDelingRoute: AuthedDelingRoute,
  AuthedShoppingRoute: AuthedShoppingRoute,
  AuthedRecipesRecipeIdRoute: AuthedRecipesRecipeIdRoute,
  AuthedRecipesNewRoute: AuthedRecipesNewRoute,
  AuthedRecipesIndexRoute: AuthedRecipesIndexRoute,
  AuthedRecipesRecipeIdEditRoute: AuthedRecipesRecipeIdEditRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
